### PR TITLE
Added file upload button to dropzone form.

### PR DESCRIPTION
**Pull request by djkiourtsis**

### CODE REVIEW

**Comment by shaunbrady** [comment]
Looks good.

**Comment by ericamador** [comment]
I noticed that this wipes out the default image overlay for the dropzone. Is this desired? Would it be possible to use the default dropzone configuration and let the end users theme it however they want?

https://github.com/enyo/dropzone/wiki/How-to-theme-Dropzone

**Comment by djkiourtsis** [comment]
@mliudev http://stackoverflow.com/questions/24469474/how-to-ouput-text-in-reactjs-without-wrapping-it-in-span?answertab=active#tab-top

**Comment by djkiourtsis** [comment]
@amadornimbis That was only because I was testing locally.  I updated it with a picture from testing on vagrant.

**Pull request merged**
